export const COLORS = {
  ADM: '#1d3557',
  ARC: '#2a9d8f',
  AUD: '#457b9d',
  CPT: '#a8dadc',
  COM: '#e76f51',
  REC: '#f4a261',
  FOR: '#e9c46a',
  ASS: '#d4a373',
  QHS: '#606c38',
  FIN: '#264653',
  ACH: '#2a9d8f',
  SCH: '#e9c46a',
  RH: '#f4a261',
  SEC: '#e76f51',
  STP: '#264653',
  MAG: '#2a9d8f',
  STV: '#e9c46a',
  CQL: '#f4a261',
  HSE: '#e76f51',
  BME: '#264653',
  PRD: '#2a9d8f',
  SIR: '#e9c46a',
  STE: '#f4a261',
  PNC: '#e76f51',
  PAR: '#264653',
  LOG: '#9d0208',
};

export const DUP_RULES = [
  {
    kw: 'facture',
    types: ['Facture', 'Factures'],
    svcs: ['COM', 'FIN', 'LOG'],
    msg: 'Vérifiez les factures similaires dans plusieurs services pour éviter les doublons.',
  },
  {
    kw: 'contrat',
    types: ['Contrat', 'Contrats'],
    svcs: ['COM', 'ADM'],
    msg: 'Plusieurs contrats semblables peuvent être archivés par différents services.',
  },
  {
    kw: 'inventaire',
    types: ['Inventaire', 'Inventaires'],
    svcs: ['COM', 'FIN'],
    msg: 'Attention aux archives d’inventaire dupliquées entre services.',
  },
];
